sudo: required
dist: trusty

addons:
  chrome: stable


language: php

php:
#This is necessary, otherwise travis will run phpunit under 5.5.38 which
#is not supported by phpunit
  - 7.1.3

#if you wanted to do tests at multiple php versions, do could do it like this
#php:
#   - 5.5
#   - 5.6
#   - 7.0

#external programs and stuff we want. docker service comes with docker-compose
services:
  - docker
  

#things to do before we build
before_install:
#`docker ps` does nothing meaningful. Just here to make sure travis has docker
  - travis_retry docker run --rm -v $(pwd):/app composer/composer install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9232 http://localhost &
  - docker-compose up -d
#start a chomedriver instance. Which is inconvenient but the only way I could get this to work.
#note that the chromedriver is outside of the docker container

before_script:
  # - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
  - cp .env.travis .env
  # - php artisan serve &

#paths to your test script
script:
#don't point this to some actual script, needs to be pointed to phpunit
#do unit tests then dusk browser tests. Note that browser tests execute from outside our docker containers
  - vendor/bin/phpunit
  - php artisan dusk
